version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - shared_network

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.2
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./open-webui_data:/app/backend/data
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
