version: '3.8'

services:
  docling:
    image: ghcr.io/docling-project/docling-serve
    container_name: docling
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - shared_network
    environment:
      - DOCLING_SERVE_ENABLE_UI=True

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.5
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ./open-webui_data:/app/backend/data
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
